[tool.isort]
line_length = 88
profile = "black"

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
exclude = [
    "cloud-intro/train.ipynb",
    "dask-machine-learning/tip-prediction.ipynb",
    "recent-developments-in-lightgbm/aws.ipynb"
]

ignore = [
    # (pycodestyle) Line too long
    "E501",
    # (pylint) Magic value used in comparison, consider replacing with a constant
    "PLR2004",
    # (flake8-pytest-style) scope='function' is implied in @pytest.fixture()
    "PT003",
    # (flake8-pytest-style) Wrong values type in @pytest.mark.parametrize expected list of tuple
    "PT007",
    # (flake8-bandit) Use of `assert` detected
    "S101",
    # (flake8-bandit) Probable insecure usage of temporary file or directory: "/tmp/model.pkl"
    "S108",
    # (flake8-bandit) `pickle` and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue
    "S301",
    # (flake8-bandit) subprocess call: check for execution of untrusted input
    "S603",
    # (flake8-simplify) use ternary operator instead of if-else
    "SIM108",
    # (pyupgrade) Unnecessary open mode parameters
    "UP015"
]
select = [
    # flake8-builtins
    "A",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # flake8-datetimez
    "DTZ",
    # pycodestyle
    "E",
    # eradicate
    "ERA",
    # pyflakes
    "F",
    # flake8-fixme
    "FIX",
    # flynt
    "FLY",
    # perflint
    "PERF",
    # pygrep-hooks
    "PGH",
    # flake8-pie
    "PIE",
    # pylint
    "PL",
    # flake8-pytest-style
    "PT",
    # flake8-pyi
    "PYI",
    # flake8-return
    "RET",
    # ruff-exclusive checks
    "RUF",
    # flake8-bandit
    "S",
    # flake8-simplify
    "SIM",
    # pyupgrade
    "UP",
]

[tool.ruff.lint.per-file-ignores]
"cloud-intro/scripts/create_random_tickets.py" = [
    # `datetime.datetime.utcnow()` used
    "DTZ003"
]
"cloud-intro/ticket_closure_lib/transformers.py" = [
    # Use `dict` instead of `Dict` for type annotation
    "UP006",
    # `typing.Dict` is deprecated, use `dict` instead
    "UP035"
]
