name: Continuous Integration

# always run CI on new commits to any branch
on: push

# default to 0 permissions
# (job-level overrides add the minimal permissions needed)
permissions:
  contents: none

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  all-successful:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - lint
    permissions:
      statuses: read
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}
