name: Continuous Integration

# always run CI on new commits to any branch
on: push

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
      - name: linting
        if: matrix.task == 'linting'
        shell: bash
        run: |
          pip install --upgrade black flake8 isort nbqa
          conda install -c conda-forge shellcheck
          make lint
  all-successful:
    # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Note that all tests succeeded
      run: echo "🎉"
